# Generated by Django 4.2.24 on 2026-05-01 22:49

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('commit_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.commit')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', validators=[api.models.validate_5mb])),
                ('cover', models.ImageField(blank=True, null=True, upload_to='companies/covers/', validators=[api.models.validate_5mb])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repositories', to=settings.AUTH_USER_MODEL)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='api.company')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, default='unread', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_media_meta', to=settings.AUTH_USER_MODEL)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='api.mediafile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blob', models.FileField(upload_to='repository_blobs/', validators=[api.models.validate_50mb])),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='api.repository')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.repository')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_question', models.TextField()),
                ('answered', models.BooleanField(db_index=True, default=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'All users'), ('users', 'Regular users'), ('admins', 'Admins')], db_index=True, default='all', max_length=20)),
                ('answerer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_answers', to=settings.AUTH_USER_MODEL)),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('object_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('guide', 'Guide'), ('reference', 'Reference'), ('api', 'API'), ('news', 'News')], db_index=True, default='guide', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All users'), ('users', 'Regular users'), ('admins', 'Admins')], db_index=True, default='all', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_company_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512)),
                ('previous_path', models.CharField(blank=True, max_length=512, null=True)),
                ('operation', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('renamed', 'Renamed')], max_length=20)),
                ('blob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit_files', to='api.fileblob')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.commit')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_versions', to='api.file')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.repository'),
        ),
        migrations.CreateModel(
            name='AuthRefreshSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='app_versions/', validators=[api.models.validate_500mb])),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(db_index=True, max_length=50)),
                ('platform', models.CharField(db_index=True, default='all', max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_app_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['visibility'], name='api_reposit_visibil_615970_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['owner_user', 'visibility'], name='api_reposit_owner_u_c0eb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['owner_company', 'visibility'], name='api_reposit_owner_c_d9c9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['name'], name='api_reposit_name_a7f264_idx'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner_company__isnull', True), ('owner_user__isnull', False)), models.Q(('owner_company__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='repository_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner_user'), condition=models.Q(('owner_user__isnull', False)), name='unique_personal_repo_ci'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner_company'), condition=models.Q(('owner_company__isnull', False)), name='unique_company_repo_ci'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status', 'created_at'], name='api_notific_recipie_b430a5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='api_notific_recipie_913487_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['repository', 'sha256'], name='api_fileblo_reposit_1b271f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblob',
            index=models.Index(fields=['sha256'], name='api_fileblo_sha256_f93859_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['repository', 'path'], name='api_file_reposit_19e7e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('repository', 'path'), name='unique_file_path_in_repository'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['answered'], name='api_faq_answere_50b4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['target_audience'], name='api_faq_target__eecbde_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['questioner', 'created_at'], name='api_faq_questio_cca973_idx'),
        ),
        migrations.AddIndex(
            model_name='entitylog',
            index=models.Index(fields=['action'], name='api_entityl_action_7575ba_idx'),
        ),
        migrations.AddIndex(
            model_name='entitylog',
            index=models.Index(fields=['content_type', 'object_id'], name='api_entityl_content_7f411b_idx'),
        ),
        migrations.AddIndex(
            model_name='entitylog',
            index=models.Index(fields=['user', 'created_at'], name='api_entityl_user_id_bd94e7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['type'], name='api_documen_type_46fb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['target_audience'], name='api_documen_target__35b303_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_company_member'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['company', 'invited_user'], name='api_company_company_62b462_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinvite',
            index=models.Index(fields=['status'], name='api_company_status_503f59_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company', 'invited_user'), name='unique_pending_company_invite'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_company_name_ci'),
        ),
        migrations.AddIndex(
            model_name='commitfile',
            index=models.Index(fields=['commit', 'path'], name='api_commitf_commit__0911e9_idx'),
        ),
        migrations.AddIndex(
            model_name='commitfile',
            index=models.Index(fields=['file'], name='api_commitf_file_id_e58bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='commitfile',
            index=models.Index(fields=['operation'], name='api_commitf_operati_1d6b5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='commitfile',
            constraint=models.UniqueConstraint(fields=('commit', 'path'), name='unique_file_path_per_commit'),
        ),
        migrations.AddConstraint(
            model_name='commitfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('blob__isnull', True), ('operation', 'deleted')), models.Q(('blob__isnull', False), ('operation__in', ['added', 'modified', 'renamed'])), _connector='OR'), name='commit_file_blob_matches_operation'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', 'created_at'], name='api_commit_reposit_2d6a02_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_hash'], name='api_commit_commit__d91b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='authrefreshsession',
            index=models.Index(fields=['user', 'expires_at'], name='api_authref_user_id_06e285_idx'),
        ),
        migrations.AddIndex(
            model_name='authrefreshsession',
            index=models.Index(fields=['token_hash'], name='api_authref_token_h_aaa99f_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['version'], name='api_appvers_version_7a4a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['platform'], name='api_appvers_platfor_756359_idx'),
        ),
        migrations.AddIndex(
            model_name='appversion',
            index=models.Index(fields=['created_at'], name='api_appvers_created_289649_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_lower_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_lower_email'),
        ),
    ]
