# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_authrefreshsession_token_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authrefreshsession",
            name="token_hash",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
