# Generated by Django 4.2.24 on 2026-05-12 11:09

import api.models.repositories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documentation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='repositories/logos/', validators=[api.models.repositories.validate_logo]),
        ),
    ]
