# Generated by Django 4.2.24 on 2026-05-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_repository_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cover',
        ),
    ]
