from django.urls import path
from . import views

urlpatterns = [
    path("registration/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("news/", views.news_view, name="news"),
    path("news/create/", views.create_news, name="create_news"),
    path("news/<int:news_id>/", views.update_news, name="update_news"),
    path("news/<int:news_id>/delete/", views.delete_news, name="delete_news"),
    path("documentation/", views.documentation_view, name="documentation"),
    path("documentation/create/", views.create_documentation, name="create_documentation"),
    path("documentation/<int:doc_id>/", views.update_documentation, name="update_documentation"),
    path("documentation/<int:doc_id>/delete/", views.delete_documentation, name="delete_documentation"),
    path("download/", views.download_view, name="download"),
    path("download/create/", views.create_version, name="create_version"),
    path("download/<int:version_id>/", views.download_file, name="download_file"),
    path("download/<int:version_id>/delete/", views.delete_version, name="delete_version"),
    path("profile/", views.get_user_profile, name="get_user_profile"),
    path("profile/update/", views.update_user_profile, name="update_user_profile"),
    path("user/role/", views.check_user_role, name="check_user_role"),
    path("QA/", views.get_QA_list, name="QA_list"),
    path("QA/create/", views.create_QA, name="QA_create"),
    path("QA/<int:qa_id>/answer/", views.answer_QA, name="answer_QA"),
    path("QA/<int:qa_id>/delete/", views.delete_QA, name="delete_QA"),
    path("project/add/", views.add_project, name="add_project"),
    path("project/get_user_projects/", views.get_user_projects, name="get_user_projects"),
    path("project/delete/<int:project_id>/", views.delete_project, name="delete_project"),
    path("project/change/<int:project_id>/", views.change_project, name="change_project"),
    path("project/download/<int:project_id>/", views.download_project, name="download_project"),
    path("project/share/<int:project_id>/", views.share_project, name="share_project"),
    path("project/shared/", views.get_shared_projects, name="get_shared_projects"),
    path("project/delete_received/<int:shared_id>/", views.delete_received, name="delete_received"),
    path("project/get_project_versions/<int:project_id>/", views.get_project_versions, name="get_project_versions"),
    path("users/", views.get_all_users, name="get_all_users"),
    path("friends/", views.get_friends, name="get_friends"),
    path("friends/add/", views.add_friend, name="add_friend"),
    path("friends/remove/", views.remove_friend, name="remove_friend"),
    path("friends/requests/", views.get_friend_requests, name="get_friend_requests"),
    path("friends/requests/sent/", views.get_sent_friend_requests, name="get_sent_friend_requests"),
    path("friends/requests/cancel/", views.cancel_friend_request, name="cancel_friend_request"),
    path("friends/requests/respond/", views.respond_friend_request, name="respond_friend_request"),
]